# Generated by Django 2.2.8 on 2022-10-14 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CBWPStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cbwp_status_code', models.CharField(max_length=5, unique=True, verbose_name='CBWP Status Code')),
                ('cbwp_status_title', models.CharField(max_length=55, unique=True, verbose_name='CBWP Status Title')),
                ('comments', models.CharField(blank=True, max_length=2000, null=True, verbose_name='CBWP Status Comments')),
            ],
            options={
                'verbose_name_plural': 'CB Work Package Statuses',
                'db_table': 'cbwp_status',
                'ordering': ['cbwp_status_code'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CostTypeClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_type_class_code', models.CharField(max_length=2, unique=True, verbose_name='Cost Type Class Code')),
                ('cost_type_class_title', models.CharField(blank=True, max_length=55, null=True, unique=True, verbose_name='Cost Type Class Title')),
            ],
            options={
                'verbose_name_plural': 'Cost Type Classes',
                'db_table': 'cost_type_class',
                'ordering': ['cost_type_class_code'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_code', models.CharField(max_length=5, unique=True, verbose_name='Department Code')),
                ('department_title', models.CharField(max_length=55, unique=True, verbose_name='Department Title')),
            ],
            options={
                'verbose_name_plural': 'Departments',
                'db_table': 'department',
                'ordering': ['department_code'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discipline_code', models.CharField(max_length=5, unique=True, verbose_name='Discipline Code')),
                ('discipline_title', models.CharField(max_length=55, unique=True, verbose_name='Discipline Title')),
            ],
            options={
                'verbose_name_plural': 'Disciplines',
                'db_table': 'discipline',
                'ordering': ['discipline_code'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EBWPStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ebwp_status_code', models.CharField(max_length=5, unique=True, verbose_name='EBWP Status Code')),
                ('ebwp_status_title', models.CharField(max_length=55, unique=True, verbose_name='EBWP Status Title')),
                ('comments', models.CharField(blank=True, max_length=2000, null=True, verbose_name='EBWP Status Comments')),
            ],
            options={
                'verbose_name_plural': 'EB Work Package Statuses',
                'db_table': 'ebwp_status',
                'ordering': ['ebwp_status_code'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EBWPType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ebwp_type_code', models.CharField(max_length=5, unique=True, verbose_name='EBWP Type Code')),
                ('ebwp_type_title', models.CharField(blank=True, max_length=55, null=True, unique=True, verbose_name='EBWP Type Title')),
                ('comments', models.CharField(blank=True, max_length=2000, null=True, verbose_name='EBWP Type Comments')),
            ],
            options={
                'verbose_name_plural': 'EBWP Types',
                'db_table': 'ebwp_type',
                'ordering': ['ebwp_type_code'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='FacilitySystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility_system_code', models.CharField(max_length=5, unique=True, verbose_name='Facility System Code')),
                ('facility_system_title', models.CharField(blank=True, max_length=55, null=True, unique=True, verbose_name='Facility System Title')),
            ],
            options={
                'verbose_name_plural': 'Facility Systems',
                'db_table': 'facility_system',
                'ordering': ['facility_system_code'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='WBSLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wbs_location_code', models.CharField(max_length=5, unique=True, verbose_name='WBS Location Code')),
                ('wbs_location_title', models.CharField(blank=True, max_length=55, null=True, unique=True, verbose_name='WBS Location Title')),
            ],
            options={
                'verbose_name_plural': 'WBS Locations',
                'db_table': 'wbs_location',
                'ordering': ['wbs_location_code'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CostType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_type_code', models.CharField(max_length=5, unique=True, verbose_name='Cost Type Code')),
                ('cost_type_title', models.CharField(blank=True, max_length=55, null=True, unique=True, verbose_name='Cost Type Title')),
                ('cost_type_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='b_wbs.CostTypeClass', verbose_name='Cost Type Class ID')),
            ],
            options={
                'verbose_name_plural': 'Cost Types',
                'db_table': 'cost_type',
                'ordering': ['cost_type_code'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CBWPType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cbwp_type_code', models.CharField(max_length=5, unique=True, verbose_name='CBWP Type Code')),
                ('cbwp_type_title', models.CharField(max_length=55, unique=True, verbose_name='CBWP Type Title')),
                ('comments', models.CharField(blank=True, max_length=2000, null=True, verbose_name='CBWP Type Comments')),
                ('ebwp_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='b_wbs.EBWPType', verbose_name='EBWP Type ID')),
            ],
            options={
                'verbose_name_plural': 'CBWP Types',
                'db_table': 'cbwp_type',
                'ordering': ['cbwp_type_code'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='FacilitySystemDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility_system_detail_code', models.CharField(max_length=15, unique=True, verbose_name='Facility System Detail Code')),
                ('facility_system_detail_title', models.CharField(blank=True, max_length=55, null=True, unique=True, verbose_name='Facility System Detail Title')),
                ('facility_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='b_wbs.FacilitySystem', verbose_name='Facility System ID')),
            ],
            options={
                'verbose_name_plural': 'Facility System Details',
                'db_table': 'facility_system_detail',
                'ordering': ['facility_system_detail_code'],
                'managed': True,
                'unique_together': {('facility_system', 'facility_system_detail_code')},
            },
        ),
    ]
