# Generated by Django 2.2.8 on 2022-10-14 21:43

from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('j_cb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CBWPAccountsReceivable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calendar_date', models.DateTimeField(verbose_name='Calendar Date')),
                ('ar_costs_currency', djmoney.models.fields.CurrencyField(choices=[('CAD', 'CA$')], default='CAD', editable=False, max_length=3, null=True)),
                ('ar_costs', djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default_currency='CAD', max_digits=18, null=True, verbose_name='Accounts Receivable Costs on Calendar Date')),
                ('comments', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Comments')),
                ('cbwp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='j_cb.CBWP', verbose_name='CBWP ID')),
            ],
            options={
                'verbose_name_plural': 'CBWP Accounts Receivable',
                'db_table': 'cbwp_accounts_receivable',
                'ordering': ['cbwp', 'calendar_date'],
                'managed': True,
                'unique_together': {('cbwp', 'calendar_date')},
            },
        ),
        migrations.CreateModel(
            name='CBWPAccountsPayable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calendar_date', models.DateTimeField(verbose_name='Calendar Date')),
                ('ap_costs_currency', djmoney.models.fields.CurrencyField(choices=[('CAD', 'CA$')], default='CAD', editable=False, max_length=3, null=True)),
                ('ap_costs', djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default_currency='CAD', max_digits=18, null=True, verbose_name='Accounts Payable Costs on Calendar Date')),
                ('comments', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Comments')),
                ('cbwp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='j_cb.CBWP', verbose_name='CBWP ID')),
            ],
            options={
                'verbose_name_plural': 'CBWP Accounts Payable',
                'db_table': 'cbwp_accounts_payable',
                'ordering': ['cbwp', 'calendar_date'],
                'managed': True,
                'unique_together': {('cbwp', 'calendar_date')},
            },
        ),
    ]
