# Generated by Django 2.2.8 on 2022-10-14 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('b_wbs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EBSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eb_schedule_code', models.CharField(max_length=55, unique=True, verbose_name='EB Schedule Code')),
                ('eb_schedule_title', models.CharField(blank=True, max_length=2000, null=True, verbose_name='EB Schedule Title')),
                ('early_start_date', models.DateTimeField(blank=True, null=True, verbose_name='EB Early Start Date')),
                ('early_finish_date', models.DateTimeField(blank=True, null=True, verbose_name='EB Early Finish Date')),
                ('early_start_to_early_finish_duration', models.IntegerField(blank=True, null=True, verbose_name='EB Early Start to Early Finish Duration')),
                ('late_start_date', models.DateTimeField(blank=True, null=True, verbose_name='EB Late Start Date')),
                ('late_finish_date', models.DateTimeField(blank=True, null=True, verbose_name='EB Late Finish Date')),
                ('late_start_to_late_finish_duration', models.IntegerField(blank=True, null=True, verbose_name='EB Late Start to Late Finish Duration')),
                ('critical_path_check', models.IntegerField(default=0, verbose_name='EB Critical Path Check')),
                ('comments', models.CharField(blank=True, max_length=2000, null=True, verbose_name='EB Comments')),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='b_wbs.Discipline', verbose_name='Discipline Code')),
                ('ebwp_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='b_wbs.EBWPType', verbose_name='EBWP Type Code')),
            ],
            options={
                'verbose_name_plural': 'EB aka L03 Schedule',
                'db_table': 'eb_schedule',
                'ordering': ['eb_schedule_code'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CBSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cb_schedule_code', models.CharField(max_length=55, unique=True, verbose_name='CB Schedule Code')),
                ('cb_schedule_title', models.CharField(blank=True, max_length=2000, null=True, verbose_name='CB Schedule Title')),
                ('early_start_date', models.DateTimeField(blank=True, null=True, verbose_name='CB Early Start Date')),
                ('early_finish_date', models.DateTimeField(blank=True, null=True, verbose_name='CB Early Finish Date')),
                ('early_start_to_early_finish_duration', models.IntegerField(blank=True, null=True, verbose_name='CB Early Start to Early Finish Duration')),
                ('late_start_date', models.DateTimeField(blank=True, null=True, verbose_name='CB Late Start Date')),
                ('late_finish_date', models.DateTimeField(blank=True, null=True, verbose_name='CB Late Finish Date')),
                ('late_start_to_late_finish_duration', models.IntegerField(blank=True, null=True, verbose_name='CB Late Start to Late Finish Duration')),
                ('critical_path_check', models.IntegerField(default=0, verbose_name='CB Critical Path Check')),
                ('comments', models.CharField(blank=True, max_length=2000, null=True, verbose_name='CB Comments')),
                ('cbwp_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='b_wbs.CBWPType', verbose_name='CBWP Type Code')),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='b_wbs.Discipline', verbose_name='Discipline Code')),
                ('eb_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='h_schedules.EBSchedule', verbose_name='EB Schedule Code')),
            ],
            options={
                'verbose_name_plural': 'CB aka L04 Schedule',
                'db_table': 'cb_schedule',
                'ordering': ['cb_schedule_code'],
                'managed': True,
            },
        ),
    ]
