# Generated by Django 2.2.8 on 2022-10-29 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('j_cb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentcontrolbudgettrends',
            name='ccbb_approval_check',
            field=models.IntegerField(default=0, verbose_name='Approval Check'),
        ),
        migrations.AddField(
            model_name='currentestimatebudgettrends',
            name='ceb_approval_check',
            field=models.IntegerField(default=0, verbose_name='Approval Check'),
        ),
        migrations.AddField(
            model_name='currentforecastbudgettrends',
            name='cfb_approval_check',
            field=models.IntegerField(default=0, verbose_name='Approval Check'),
        ),
    ]
