# Generated by Django 2.2.8 on 2022-10-29 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('j_cb', '0002_auto_20221029_1130'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currentcontrolbudgettrends',
            old_name='ccbb_approval_check',
            new_name='ccb_approval_check',
        ),
    ]
