# Generated by Django 2.2.8 on 2022-10-14 21:43

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('f_contracts', '0001_initial'),
        ('j_cb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimRoute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_route_code', models.CharField(max_length=5, unique=True, verbose_name='Claim Type Code')),
                ('claim_route_title', models.CharField(max_length=55, unique=True, verbose_name='Claim Type Title')),
            ],
            options={
                'verbose_name_plural': 'Claims - Route',
                'db_table': 'claim_route',
                'ordering': ['claim_route_code'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ClaimType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_type_code', models.CharField(max_length=5, unique=True, verbose_name='Claim Type Code')),
                ('claim_type_title', models.CharField(max_length=55, unique=True, verbose_name='Claim Type Title')),
                ('comments', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Comments')),
            ],
            options={
                'verbose_name_plural': 'Claims - Types',
                'db_table': 'claim_type',
                'ordering': ['claim_type_code'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CBWPClaimDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Claim Number')),
                ('claim_initiation_date', models.DateTimeField(verbose_name='Claim Initiation Date')),
                ('claim_title', models.CharField(max_length=55, unique=True, verbose_name='Claim Title')),
                ('claim_summary', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Claim Summary')),
                ('cbwp_hours_change_sought', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=18, null=True, verbose_name='CBWP Hours Change Sought')),
                ('cbwp_hours_change_approved', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=18, null=True, verbose_name='CBWP Hours Change Approved')),
                ('cbwp_costs_change_sought', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=18, null=True, verbose_name='CBWP Costs Change Sought')),
                ('cbwp_costs_change_approved', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=18, null=True, verbose_name='CBWP Costs Change Approved')),
                ('cbwp_daily_extension_sought', models.IntegerField(blank=True, null=True, verbose_name='CBWP Daily Extension Sought')),
                ('cbwp_daily_extension_approved', models.IntegerField(blank=True, null=True, verbose_name='CBWP Daily Extension Approved')),
                ('comments', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Comments')),
                ('cbwp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='j_cb.CBWP', verbose_name='CBWP ID')),
                ('claim_route', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='m_claims.ClaimRoute', verbose_name='Claim Route ID')),
                ('claim_type', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='m_claims.ClaimType', verbose_name='Claim Type ID')),
            ],
            options={
                'verbose_name_plural': 'CBWP Claims',
                'db_table': 'cbwp_claim',
                'managed': True,
                'unique_together': {('cbwp', 'claim_number')},
            },
        ),
        migrations.CreateModel(
            name='CBWPClaimDetailContractClauseReferences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Comments')),
                ('cbwp_claim', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='m_claims.CBWPClaimDetail', verbose_name='CBWP Claim Detail ID')),
                ('contract_clause', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='f_contracts.ContractClauses', verbose_name='Contract Clause ID')),
            ],
            options={
                'verbose_name_plural': 'CBWP Claims With Contract Clauses',
                'db_table': 'cbwp_claim_clause',
                'managed': True,
                'unique_together': {('cbwp_claim', 'contract_clause')},
            },
        ),
    ]
