# Generated by Django 2.2.8 on 2022-10-14 21:43

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('g_measures', '0001_initial'),
        ('e_commodities', '0001_initial'),
        ('b_wbs', '0001_initial'),
        ('a_hr', '0001_initial'),
        ('h_schedules', '0001_initial'),
        ('f_contracts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EBWP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ebwp_code', models.CharField(max_length=55, unique=True, verbose_name='EBWP Code')),
                ('ebwp_title', models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='EBWP Title')),
                ('ebwp_discretionary_start_date', models.DateTimeField(blank=True, null=True, verbose_name='EBWP Discretionary Start Date')),
                ('ebwp_discretionary_finish_date', models.DateTimeField(blank=True, null=True, verbose_name='EBWP Discretionary Finish Date')),
                ('ebwp_comments', models.CharField(blank=True, max_length=200, null=True, verbose_name='EBWP Comments')),
                ('ebwp_primary_contact', models.CharField(blank=True, max_length=100, null=True, verbose_name='EBWP Primary Contact or Owner')),
                ('ebwp_secondary_contact', models.CharField(blank=True, max_length=100, null=True, verbose_name='EBWP Secondary Contact')),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='EBWP Quantity')),
                ('ebwp_hours', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=18, null=True, verbose_name='EBWP Hours')),
                ('ebwp_costs_currency', djmoney.models.fields.CurrencyField(choices=[('CAD', 'CA$')], default='CAD', editable=False, max_length=3, null=True)),
                ('ebwp_costs', djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default=Decimal('0'), default_currency='CAD', max_digits=18, null=True, verbose_name='EBWP Costs')),
                ('commodity', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='e_commodities.Commodity', verbose_name='EBWP Commodity ID')),
                ('commodity_type', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='e_commodities.CommodityType', verbose_name='EBWP Commodity Type ID')),
                ('contract', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='f_contracts.Contract', verbose_name='EBWP Contract ID')),
                ('cost_type', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='b_wbs.CostType', verbose_name='EBWP Cost Type ID')),
                ('department', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='b_wbs.Department', verbose_name='EBWP Department ID')),
                ('discipline', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='b_wbs.Discipline', verbose_name='EBWP Discipline ID')),
                ('eb_schedule', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='h_schedules.EBSchedule', verbose_name='EBWP Schedule Activity Code')),
                ('ebwp_sibling', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='i_eb.EBWP', verbose_name='EBWP Sibling ID')),
                ('ebwp_status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='b_wbs.EBWPStatus', verbose_name='EBWP Status ID')),
                ('ebwp_type', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='b_wbs.EBWPType', verbose_name='EBWP Type ID')),
                ('facility_system_detail', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='b_wbs.FacilitySystemDetail', verbose_name='EBWP Facility System Detail ID')),
                ('uom', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='g_measures.UOM', verbose_name='CBWP UOM ID')),
                ('wbs_location', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='b_wbs.WBSLocation', verbose_name='WBS Location ID')),
            ],
            options={
                'verbose_name_plural': 'EBWP Details',
                'db_table': 'ebwp',
                'ordering': ['ebwp_code'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EBWPAudit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ebwp_id', models.IntegerField(verbose_name='EBWP ID')),
                ('ebwp_code', models.CharField(max_length=55, verbose_name='EBWP Code')),
                ('ebwp_title', models.CharField(blank=True, max_length=200, null=True, verbose_name='EBWP Title')),
                ('ebwp_status_id', models.IntegerField(verbose_name='EB Status ID')),
                ('cost_type_id', models.IntegerField(verbose_name='Cost Type ID')),
                ('ebwp_type_id', models.IntegerField(verbose_name='EB Type ID')),
                ('department_id', models.IntegerField(verbose_name='Department ID')),
                ('discipline_id', models.IntegerField(verbose_name='Discipline ID')),
                ('wbs_location_id', models.IntegerField(verbose_name='WBS Location ID')),
                ('contract_id', models.IntegerField(verbose_name='EBWP Contract ID')),
                ('commodity_type_id', models.IntegerField(verbose_name='EBWP Commodity Type ID')),
                ('commodity_id', models.IntegerField(verbose_name='EBWP Commodity ID')),
                ('facility_system_detail_id', models.IntegerField(verbose_name='EBWP Facility System Detail ID')),
                ('eb_schedule_id', models.IntegerField(verbose_name='EB Schedule ID')),
                ('ebwp_discretionary_start_date', models.DateTimeField(blank=True, null=True, verbose_name='EBWP Discretionary Start Date')),
                ('ebwp_discretionary_finish_date', models.DateTimeField(blank=True, null=True, verbose_name='EBWP Discretionary Finish Date')),
                ('ebwp_sibling_id', models.IntegerField(blank=True, null=True, verbose_name='EB Sibling ID')),
                ('ebwp_comments', models.CharField(blank=True, max_length=200, null=True, verbose_name='EBWP Comments')),
                ('ebwp_primary_contact', models.CharField(blank=True, max_length=2000, null=True, verbose_name='EBWP Primary Contact or Owner')),
                ('ebwp_secondary_contact', models.CharField(blank=True, max_length=2000, null=True, verbose_name='EBWP Secondary Contact or Owner')),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='EBWP Quantity')),
                ('uom_id', models.IntegerField(verbose_name='EBWP UOM ID')),
                ('ebwp_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='EBWP Hours')),
                ('ebwp_costs', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='EBWP Costs')),
                ('dml_action', models.CharField(blank=True, max_length=2000, null=True, verbose_name='DML Action')),
                ('modified_by', models.CharField(max_length=55, verbose_name='Modified By')),
                ('modified_date', models.DateTimeField(verbose_name='Modified Date')),
            ],
            options={
                'verbose_name_plural': 'EBWP Details - Audit',
                'db_table': 'ebwp_audit',
                'ordering': ['ebwp_code'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OriginalEstimateBudget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oeb_code', models.CharField(max_length=55, unique=True, verbose_name='OEB Code')),
                ('oeb_title', models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='OEB Title')),
                ('oeb_comments', models.CharField(blank=True, max_length=200, null=True, verbose_name='OEB Comments')),
                ('oeb_qty', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='OEB Quantity')),
                ('oeb_hours', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=18, null=True, verbose_name='OEB Hours')),
                ('oeb_costs', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='OEB Costs')),
                ('cost_type', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='b_wbs.CostType', verbose_name='OEB Cost Type ID')),
                ('department', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='b_wbs.Department', verbose_name='OEB Department ID')),
                ('oeb_uom', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='g_measures.UOM', verbose_name='eb UOM ID')),
            ],
            options={
                'verbose_name_plural': 'Original Estimate Budget',
                'db_table': 'tm_oeb',
                'ordering': ['oeb_code'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EBWPNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_no', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Note Number')),
                ('title', models.CharField(max_length=100, verbose_name='EBWP Note Title')),
                ('comments', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Comments')),
                ('ebwp', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='i_eb.EBWP', verbose_name='EBWP ID')),
            ],
            options={
                'verbose_name_plural': 'EBWP Notes',
                'db_table': 'ebwp_note',
                'ordering': ['title'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EBWPAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment_code', models.CharField(max_length=100, unique=True, verbose_name='Attachment Code')),
                ('attachment_title', models.CharField(max_length=100, verbose_name='Attachment Title')),
                ('revision_number', models.CharField(blank=True, max_length=3, null=True, verbose_name='Revision No')),
                ('revision_status', models.CharField(blank=True, max_length=55, null=True, verbose_name='Revision Status')),
                ('release_date', models.DateTimeField(blank=True, null=True, verbose_name='Release Date')),
                ('comments', models.CharField(blank=True, max_length=2000, null=True, verbose_name='EBWP Attachment Comments')),
                ('ebwp_attachment', models.FileField(blank=True, null=True, upload_to='EBWPAttachments/', verbose_name='EBWP Attachments')),
                ('ebwp_url', models.URLField(blank=True, max_length=250, null=True, verbose_name='EBWP URL')),
                ('ebwp', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='i_eb.EBWP', verbose_name='EBWP ID')),
            ],
            options={
                'verbose_name_plural': 'EBWP Attachments',
                'db_table': 'ebwp_attachment',
                'ordering': ['attachment_code'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OEBRaciInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Comments')),
                ('personnel', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='a_hr.Personnel', verbose_name='Personnel ID')),
                ('raci', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='a_hr.RaciMatrixDefinition', verbose_name='Raci ID')),
                ('tm_oeb', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='i_eb.OriginalEstimateBudget', verbose_name='OEB ID')),
            ],
            options={
                'verbose_name_plural': 'Original Estimate Budget RACI Information',
                'db_table': 'tm_oeb_raci_info',
                'managed': True,
                'unique_together': {('tm_oeb', 'personnel', 'raci')},
            },
        ),
        migrations.CreateModel(
            name='EBWPRaciInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Comments')),
                ('ebwp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='i_eb.EBWP', verbose_name='EBWP ID')),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a_hr.Personnel', verbose_name='Personnel ID')),
                ('raci', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a_hr.RaciMatrixDefinition', verbose_name='Raci ID')),
            ],
            options={
                'verbose_name_plural': 'EBWP RACI Information',
                'db_table': 'ebwp_raci_info',
                'managed': True,
                'unique_together': {('ebwp', 'personnel', 'raci')},
            },
        ),
        migrations.CreateModel(
            name='EBWPCostDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_no', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Item Number')),
                ('item_title', models.CharField(max_length=55, verbose_name='Item Title')),
                ('item_costs', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Item Costs')),
                ('comments', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Comments')),
                ('cost_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='b_wbs.CostType', verbose_name='EBWP Detail Cost Type ID')),
                ('ebwp', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='i_eb.EBWP', verbose_name='EBWP ID')),
            ],
            options={
                'verbose_name_plural': 'EBWP Cost Details',
                'db_table': 'ebwp_cost_detail',
                'ordering': ['item_title'],
                'managed': True,
                'unique_together': {('item_title', 'cost_type', 'ebwp')},
            },
        ),
    ]
