# Generated by Django 2.2.8 on 2022-10-29 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('i_eb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='originalestimatebudget',
            name='oeb_approval_check',
            field=models.IntegerField(default=0, verbose_name='Approval Check'),
        ),
    ]
