# Generated by Django 2.2.8 on 2022-11-01 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('b_wbs', '0001_initial'),
        ('g_measures', '0001_initial'),
        ('i_eb', '0002_originalestimatebudget_oeb_approval_check'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentEstimateBudget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ceb_code', models.CharField(max_length=55, unique=True, verbose_name='CEB Code')),
                ('ceb_title', models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='CEB Title')),
                ('ceb_comments', models.CharField(blank=True, max_length=200, null=True, verbose_name='CEB Comments')),
                ('ceb_qty', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='CEB Quantity')),
                ('ceb_hours', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=18, null=True, verbose_name='CEB Hours')),
                ('ceb_costs', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='CEB Costs')),
                ('ceb_approval_check', models.IntegerField(default=0, verbose_name='Approval Check')),
                ('oeb_ceb_trend_import_check', models.IntegerField(default=0, verbose_name='Import from OEB and CEB Trend Check')),
                ('ceb_uom', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='g_measures.UOM', verbose_name='CEB UOM ID')),
                ('cost_type', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='b_wbs.CostType', verbose_name='CEB Cost Type ID')),
                ('department', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='b_wbs.Department', verbose_name='CEB Department ID')),
            ],
            options={
                'verbose_name_plural': 'Current Estimate Budget',
                'db_table': 'tm_ceb',
                'ordering': ['ceb_code'],
                'managed': True,
            },
        ),
    ]
