# Generated by Django 2.2.8 on 2022-10-14 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('g_measures', '0001_initial'),
        ('j_cb', '0001_initial'),
        ('e_commodities', '0001_initial'),
        ('d_mm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_component_code', models.CharField(max_length=25, unique=True, verbose_name='Project Component Code')),
                ('project_component_title', models.CharField(blank=True, max_length=55, null=True, unique=True, verbose_name='Project Component Title')),
                ('comments', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Project Component Comments')),
            ],
            options={
                'verbose_name_plural': 'Project Components',
                'db_table': 'project_component',
                'ordering': ['project_component_code'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ProjectDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_document_code', models.CharField(max_length=25, unique=True, verbose_name='Project Document Code')),
                ('project_document_title', models.CharField(max_length=100, unique=True, verbose_name='Project Document Title')),
                ('revision_number', models.CharField(blank=True, max_length=3, null=True, verbose_name='Revision No')),
                ('revision_status', models.CharField(blank=True, max_length=55, null=True, verbose_name='Revision Status')),
                ('release_date', models.DateTimeField(blank=True, null=True, verbose_name='Release Date')),
                ('comments', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Project Document Comments')),
                ('document_attachment', models.FileField(blank=True, null=True, upload_to='Documents/', verbose_name='Document Attachment')),
                ('document_url', models.URLField(blank=True, max_length=250, null=True, verbose_name='Document URL')),
            ],
            options={
                'verbose_name_plural': 'Project Documents',
                'db_table': 'project_document',
                'ordering': ['project_document_code'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ProjectDocumentComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_document_component_code', models.CharField(default='Test', max_length=25, unique=True, verbose_name='Project Unified Document Component Code')),
                ('project_document_component_title', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Project Unified Document Component Code Title')),
                ('project_component', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='k_quantum.ProjectComponent', verbose_name='Project Component ID')),
                ('project_document', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='k_quantum.ProjectDocument', verbose_name='Project Document ID')),
            ],
            options={
                'verbose_name_plural': 'Project Unified Documents Components',
                'db_table': 'project_document_component',
                'ordering': ['project_document_component_code'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CBWPQuantum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantum_code', models.CharField(max_length=100, unique=True, verbose_name='CBWP Quantum Code')),
                ('quantum_title', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='CBWP Quantum Title')),
                ('cad_id', models.CharField(blank=True, max_length=55, null=True, verbose_name='CAD ID')),
                ('quantity', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True, verbose_name='Quantity')),
                ('mp_01_date_p', models.DateTimeField(blank=True, null=True, verbose_name='1st Planned MP Date')),
                ('mp_01_date_e', models.DateTimeField(blank=True, null=True, verbose_name='1st Earned MP Date')),
                ('mp_02_date_p', models.DateTimeField(blank=True, null=True, verbose_name='2nd Planned MP Date')),
                ('mp_02_date_e', models.DateTimeField(blank=True, null=True, verbose_name='2nd Earned MP Date')),
                ('mp_03_date_p', models.DateTimeField(blank=True, null=True, verbose_name='3rd Planned MP Date')),
                ('mp_03_date_e', models.DateTimeField(blank=True, null=True, verbose_name='3rd Earned MP Date')),
                ('mp_04_date_p', models.DateTimeField(blank=True, null=True, verbose_name='4th Planned MP Date')),
                ('mp_04_date_e', models.DateTimeField(blank=True, null=True, verbose_name='4th Earned MP Date')),
                ('mp_05_date_p', models.DateTimeField(blank=True, null=True, verbose_name='05th Planned Milepost Date')),
                ('mp_05_date_e', models.DateTimeField(blank=True, null=True, verbose_name='05th Earned Milepost Date')),
                ('mp_06_date_p', models.DateTimeField(blank=True, null=True, verbose_name='06th Planned Milepost Date')),
                ('mp_06_date_e', models.DateTimeField(blank=True, null=True, verbose_name='06th Earned Milepost Date')),
                ('mp_07_date_p', models.DateTimeField(blank=True, null=True, verbose_name='07th Planned Milepost Date')),
                ('mp_07_date_e', models.DateTimeField(blank=True, null=True, verbose_name='07th Earned Milepost Date')),
                ('mp_08_date_p', models.DateTimeField(blank=True, null=True, verbose_name='08th Planned Milepost Date')),
                ('mp_08_date_e', models.DateTimeField(blank=True, null=True, verbose_name='08th Earned Milepost Date')),
                ('mp_09_date_p', models.DateTimeField(blank=True, null=True, verbose_name='09th Planned Milepost Date')),
                ('mp_09_date_e', models.DateTimeField(blank=True, null=True, verbose_name='09th Earned Milepost Date')),
                ('mp_10_date_p', models.DateTimeField(blank=True, null=True, verbose_name='10th Planned Milepost Date')),
                ('mp_10_date_e', models.DateTimeField(blank=True, null=True, verbose_name='10th Earned Milepost Date')),
                ('comments', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Comments')),
                ('cbwp', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='j_cb.CBWP', verbose_name='CBWP ID')),
                ('commodity_detail', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='e_commodities.CommodityDetail', verbose_name='Commodity Detail ID')),
                ('material_status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='d_mm.MaterialStatus', verbose_name='Material Status ID')),
                ('milepost_template', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='g_measures.MilepostTemplate', verbose_name='Milepost Template ID')),
                ('project_document_component', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='k_quantum.ProjectDocumentComponent', verbose_name='Project Document Component ID')),
            ],
            options={
                'verbose_name_plural': 'CBWP Quantum',
                'db_table': 'cbwp_quantum',
                'ordering': ['quantum_code'],
                'managed': True,
            },
        ),
    ]
